// This file is kept for compatibility but the fragment is now defined in the GraphQL files
// and types are generated by graphql-codegen

export type { ResponsiveImageFragmentFragment } from '@lib/datocms/types';

// Re-export for backward compatibility
export { ResponsiveImageFragmentFragmentDoc as ResponsiveImageFragment } from '@lib/datocms/types';
